lhand_motor:
  ID: 0
  Return_Delay_Time: 0
  Operating_Mode: 5
  torque_constant: 1.15
  
# Above torque_constant is the value for XC330-T288-T: (Stall Torque [Nm]) / (Current at Stall Torque [A]) = 0.92 / 0.80

# I/You have to chenge this value when I change types of motors.

# Operation_Mode
## 3 for Position Control Mode
## 5 for Current-based Position Control Mode