name: ROS 2 Jazzy CI

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  industrial_ci:
    name: Jazzy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and test
        uses: ros-industrial/industrial_ci@master
        env:
          ROS_DISTRO: jazzy
          ROS_REPO: main
          TARGET_WORKSPACE: jsk_hand/dynamixel_detachable_hand
          UPSTREAM_WORKSPACE: >-
            .github/ros2_jazzy.repos
            -dynamixel-workbench/dynamixel_workbench
            -jsk_roseus/jsk_roseus
            -jsk_roseus/roseus_tutorials
          BEFORE_INSTALL: >-
            sudo apt-get update &&
            sudo apt-get install -y software-properties-common &&
            sudo add-apt-repository -y ppa:k-okada/euslisp &&
            sudo apt-get update
          ADDITIONAL_DEBS: >-
            euslisp-dev
            jskeus-dev
          ROSDEP_SKIP_KEYS: >-
            euslisp-dev
            jskeus-dev
